# testlib : bitmap_all.o bitmap_any.o bitmap_contains.o bitmap_count.o bitmap_dump.o 
# 		  bitmap_expand.o bitmap_flip.o bitmap_mark.o bitmap_none.o bitmap_plain.o bitmap_reset.o
# 		  bitmap_scan.o bitmap_scan_and_flip.o bitmap_set.o bitmap_set_all.o bitmap_set_multiple.o
# 		  bitmap_size.o bitmap_test.o hash_apply.o hash_delete.o hash_etc.o hash_find.o hash_insert.o
# 		  hash_plain.o hash_replace.o list_frontback.o list_insert.o list_insert_ordered.o 
# 		  list_maxminsizeempty.o list_plain.o list_pops.o list_pushes.o list_remove.o list_reverse.o
# 		  list_shuffle.o

# testlib : list.o bitmap.o hash.o main.o
# 	gcc -o list.out bitmap.out hash.out main.o

# list.o : list.c
# 	gcc -c -o list.o list.c

# bitmap.o : bitmap.c
# 	gcc -c -o bitmap.o bitmap.c

# hash.o : hash.c
# 	gcc -c -o hash.o hash.c

# main.o : main.c
# 	gcc -c -o main.o main.c

clean:
	rm *.output
	rm *.result
	rm Score.txt
